version: "3.9"
networks:
  greenfield-network:
    driver: bridge
services:
  db:
    image: postgres
    container_name: greenfield_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    networks:
      - greenfield-network
    volumes:
      - pgdata:/data/postgres
  api:
    build: .
    command: ["/wait-for-it.sh", "db:5432", "-t", "30", "--", "java", "-jar", "api.jar"]
    container_name: greenfield_api
    restart: always
    environment:
      DB_HOST: db
    ports:
      - 8080:8080
    networks:
      - greenfield-network
    depends_on:
      - db
volumes:
  pgdata:
    driver: local