spring:

    profiles.active: dev

    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost/postgres
        username: root
        password: root

    jpa:
        database: POSTGRESQL
        show-sql: true
        hibernate.ddl-auto: create-drop

    banner.location: classpath:banner.txt

    jackson.deserialization:
        fail-on-unknown-properties: true

server.port: 8080
