spring:
    profiles.active: dev
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://${DB_HOST:localhost}/postgres
        username: root
        password: root
        hikari.connection-init-sql: SET TIME ZONE 'UTC'
    jpa:
        database: POSTGRESQL
        show-sql: true
    banner.location: classpath:banner.txt
    jackson:
        deserialization:
            fail-on-unknown-properties: true
        property-naming-strategy: SNAKE_CASE
    mvc.throw-exception-if-no-handler-found: true
    web.resources.add-mappings: false
server.port: 8080
