spring:
    profiles.active: dev
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost/postgres
        username: root
        password: root
    jpa:
        database: POSTGRESQL
        show-sql: true
    banner.location: classpath:banner.txt
    jackson.deserialization.fail-on-unknown-properties: true
    mvc.throw-exception-if-no-handler-found: true
    web.resources.add-mappings: false
server.port: 8080
